test_color_name_to_hex (__main__.TestExercice) ... ok
test_list_to_dict (__main__.TestExercice) ... FAIL
test_odd_integer_for_loop (__main__.TestExercice) ... FAIL
test_odd_integer_list_comprehension (__main__.TestExercice) ... FAIL
test_word_dict_comprehension (__main__.TestExercice) ... ERROR
test_word_dict_for_loop (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_word_dict_comprehension (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 77, in test_word_dict_comprehension
    output = exercice.word_dict_comprehension(words)
TypeError: word_dict_comprehension() takes 0 positional arguments but 1 was given

======================================================================
ERROR: test_word_dict_for_loop (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 66, in test_word_dict_for_loop
    output = exercice.word_dict_for_loop(words)
TypeError: word_dict_for_loop() takes 0 positional arguments but 1 was given

======================================================================
FAIL: test_list_to_dict (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_list_to_dict
    'Mauvaise reponse'
AssertionError: Lists differ: [{}, {}] != [{'a': 0, 'b': 1, 'z': 2, 'patate': 3}, {'a[33 chars]: 3}]

First differing element 0:
{}
{'a': 0, 'b': 1, 'z': 2, 'patate': 3}

- [{}, {}]
+ [{'a': 0, 'b': 1, 'patate': 3, 'z': 2},
+  {'2': 1, 'a': 0, 'hello': 2, 'tigre': 3}] : Mauvaise reponse

======================================================================
FAIL: test_odd_integer_for_loop (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 50, in test_odd_integer_for_loop
    'Mauvaise reponse'
AssertionError: Lists differ: [] != [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23[40 chars], 45]

Second list contains 23 additional elements.
First extra element 0:
1

- []
+ [1,
+  3,
+  5,
+  7,
+  9,
+  11,
+  13,
+  15,
+  17,
+  19,
+  21,
+  23,
+  25,
+  27,
+  29,
+  31,
+  33,
+  35,
+  37,
+  39,
+  41,
+  43,
+  45] : Mauvaise reponse

======================================================================
FAIL: test_odd_integer_list_comprehension (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 61, in test_odd_integer_list_comprehension
    'Mauvaise reponse'
AssertionError: Lists differ: [] != [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]

Second list contains 12 additional elements.
First extra element 0:
1

- []
+ [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23] : Mauvaise reponse

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3, errors=2)
